version: '3.8'

services:
  funchat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funchat-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=funchat_super_secret_jwt_key_123!
      - PORT=5000
